### ISSUE TITLE
Practica Architec

### ISSUE THREAD

**Issue by edgarmauricio123** [SistemasTecTlaxiaco/actividad-3-practica-architect-edgarmauricio123-11#1]
[PRACTICA ARCHITEC.pdf](https://github.com/user-attachments/files/16858803/PRACTICA.ARCHITEC.pdf)

**Comment by Jaczibeth** [comment]
De acuerdo a la rubrica cumple todos los requisitos por lo que tienen el 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
